twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        nav_bar_business: '@App\Service\Business\NavBarBusiness'
        console_util: '@App\Service\Util\Console\Console'